package proyecto;

public enum Producto {
	MANZANA, PERA, JITOMATE, CEBOLLA, PLATANO, NARANJA, PIÑA, MANGO, MELON, LECHUGA, ESPINACA, BROCOLI,
	AJO, ZANAHORIA, BERENJENA, SANDIA, KIWI, AGUACATE, UVA, DURAZNO, PAPAYA, LIMON, CILANTRO, PEREJIL
}